server:
  extraFlags:
  - web.enable-lifecycle
  - web.enable-remote-write-receiver
  - enable-feature=exemplar-storage
  - enable-feature=otlp-write-receiver
  resources: {}
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 512Mi

prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

# extraScrapeConfigs: |
#   - job_name: 'otel-collector'
#     scrape_interval: 15s
#     params:
#       module: [http_2xx]
#     static_configs:
#       - targets:
#         - 'opentelemetry-collector:9201'
