services:
  newsfeedapi:
    image: localhost:5000/newsfeed-api
    build:
      context: .
      dockerfile: src/NewsfeedAPI/Dockerfile
    environment:
       - OTEL_SERVICE_LINK=http://opentelemetry-collector.otel-demo.svc.cluster.local
    networks:
        - app

  platformapi:
    image: localhost:5000/platform-api
    build:
      context: .
      dockerfile: src/PlatformAPI/Dockerfile
    environment:
       - OTEL_SERVICE_LINK=http://opentelemetry-collector.otel-demo.svc.cluster.local
    networks:
        - app
networks:
  app:
    