apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed
spec:
  selector:
    matchLabels:
      app: newsfeed-api
  template:
    metadata:
      labels:
        app: newsfeed-api
    spec:
      containers:
      - name: newsfeed-api
        image: localhost:5000/newsfeed-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
