apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsfeed-api
  namespace: app-demo
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: newsfeed-api
    app.kubernetes.io/instance: newsfeed-api
    app.kubernetes.io/version: 1.0.0
spec:
  selector:
    matchLabels:
      app: newsfeed-api
  template:
    metadata:
      labels:
        app: newsfeed-api
        app.kubernetes.io/component: api
        app.kubernetes.io/name: newsfeed-api
        app.kubernetes.io/instance: newsfeed-api
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: newsfeed-api
        image: localhost:5000/newsfeed-api:20240817
        resources:
          limits:
            memory: "512Mi"
            cpu: "512m"
        ports:
        - containerPort: 8080
        env:
        - name: TestEnv
          value: "Test Env"
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://opentelemetry-collector.otel-demo.svc.cluster.local
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.namespace=app-demo,service.version=1.1.0,test.author=hcphi
        volumeMounts:
        - name: config-volume
          mountPath: /app/appsettings.Development.json
          subPath: appsettings.Development.json
      volumes:
      - name: config-volume
        configMap:
          name: newsfeed-development-config
