{
 "title": "Logs Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {}
   },
   {
    "name": "app_name",
    "query": {}
   },
   { "name": "filter" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity_text) (count_over_time({service_namespace=\"$namespace\", service_name=\"$app_name\"} |= `$filter` | logfmt | severity_text =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Method Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Method) (count_over_time({service_namespace=\"$namespace\", service_name=\"$app_name\"} |= `$filter` | logfmt | Method =~ `.+` [$__auto]))"
    }
   ]
  },
  {
   "title": "Top 10 Endpoints Error",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(RequestPath) (count_over_time({service_namespace=\"$namespace\", service_name=\"$app_name\"} |= `$filter` | logfmt | RequestPath =~ `.+` [$__auto])))"
    }
   ]
  },
  {
   "title": "Top 50 Endpoint Error",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "topk(50, sum by(RequestPath) (count_over_time({service_namespace=\"$namespace\", service_name=\"$app_name\"} |= `$filter` | severity_text = `Error` [$__auto])))"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{service_namespace=\"$namespace\", service_name=\"$app_name\"} |= `$filter`"
    }
   ]
  }
 ]
}