adminUser: admin
adminPassword: admin123

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      uid: prometheus
      type: prometheus
      url: http://prometheus-demo-server
      access: proxy
      isDefault: true
      editable: true
    - name: Loki
      uid: loki
      type: loki
      url: http://loki:3100
      access: proxy
      isDefault: false
      editable: true
      jsonData:
        derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id"
          matcherType: label
          name: "TraceID"
          url: "$${__value.raw}"
          urlDisplayLabel: ""
    - name: Tempo
      uid: tempo
      type: tempo
      url: http://tempo:3100
      access: proxy
      isDefault: false
      editable: true
      jsonData:
        tracesToLogsV2:
          customQuery: false
          datasourceUid: loki
          filterBySpanID: false
          filterByTraceID: false

# dashboardProviders:
#   dashboardproviders.yaml:
#     apiVersion: 1
#     providers:
#     - name: 'default'
#       orgId: 1
#       folder: ''
#       type: file
#       disableDeletion: false
#       editable: true
#       options:
#         path: /var/lib/grafana/dashboards/default

# dashboards:
#   default:
#     # Thêm dashboard từ các file JSON cụ thể
#     dashboard-app-monitor:
#       file: ./dashboard-app-monitor.json
#     dashboard-k8s-monitor:
#       file: ./dashboard-k8s-monitor.json
#     dashboard-node-monitor:
#       file: ./dashboard-node-monitor.json
#     dashboard-pod-monitor:
#       file: ./dashboard-pod-monitor.json
