apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "newsfeed-api.fullname" . }}-configmap  
  namespace: {{ .Values.global.namespace }}  
data:
{{ (.Files.Glob "configs/*").AsConfig | indent 2 }}